=head1 NAME

Whatpm::CSS::SelectorsParser - A Selectors Parser

=head1 SYNOPSIS

  use Whatpm::CSS::SelectorsParser;
  my $parser = Whatpm::CSS::SelectorsParser->new;
  $parsed_selectors = $parser->parse_string ($selectors);

=head1 DESCRIPTION

The C<Whatpm::CSS::SelectorsParser> is a parser for Selectors, the
element pattern language used in CSS.  It parses a Selectors string
into parsed data structure, if the input is valid, or reports a parse
error, otherwise.  In addition, it provides a method to compute the
specificity of a parsed selector.

=head1 METHODS

=over 4

=item $parser = Whatpm::CSS::SelectorsParser->new

Creates a new instance of the Selectors parser.

=item $parsed = $parser->parse_string ($selectors)

Parses a character string.  If it is a valid group of selectors, the
method returns the parsed group of selectors data structure.
Otherwise, it returns C<undef>.

=item $specificity = $parser->get_selector_specificity ($parsed_selector)

Returns the specificity of a parsed selector data structure.  Note
that the input has to be a I<selector>, not a I<group of selectors>.

The return value is an array reference with four values: The C<style>
attribute flag (always C<0>), I<a>, I<b>, and I<c>.

=back

=head1 PARAMETERS

Following parameters can be specified on a parser object:

=over 4

=item $parser->{href} = URL

The URL in which the input selectors string is found, if available.
This value is used to set the C<href> parameter to the 
C<< $parser->{onerror} >> handler.

=item $parser->{lookup_namespace_uri} = CODE

The C<CODE> reference used to resolve namespce prefixes and to obtain
the default namespace.

The code would be invoked during the parsing with an argument.  The
argument is C<undef>, it must return the default namespace URL.
Otherwise, it must return the namespace URL bound to the specified
namespace prefix.

If the namespace URL is explicitly given for the prefix (or the
default namespace), the URL must be returned.  If the prefix (or the
default namespace) is bound to the null namespace, the empty string
must be returned.  (Note that this is incompatible with the
C<lookup_namespace_uri> method on the C<Node> object.)  Otherwise,
i.e. the namespace prefix (or the default namespace) is not bound to
any namespace, C<undef> must be returned.

=item $parser->{onerror} = CODE

The C<CODE> reference to which any errors and warnings during the
parsing is reported.  The code would receive the following name-value
pairs:

=over 4

=item type (string, always specified)

A short string describing the kind of the error.  Descriptions of
error types are available at
<http://suika.fam.cx/gate/2007/html/error-description#{type}>, where
I<{type}> is an error type string.

For the list of error types, see
<http://suika.fam.cx/gate/2007/html/error-description#langtag-errors>.

=item level (string, always specified)

A character representing the level or severity of the error, which is
one of the following characters: C<m> (violation to a MUST-level
requirement), C<s> (violation to a SHOULD-level requirement), C<w> (a
warning), and C<i> (an informational notification).

=item token (always specified)

A L<Whatpm::CSS::Tokenizer> token where the error is detected.

=item uri (a reference to string, possibly missing)

The URL in which the input selectors string is found.  The value is
always same as C<< $parser->{href} >> in this parser.

=item value (string, possibly missing)

A part of the input, in which an error is detected.

=back

=item $parser->{pseudo_class} = {class_name => 1, class_name => 1, ...}

The list of pseudo-classes supported by the implementation,
represented as a hash reference, where the hash key is the lowercased
pseudo-class name and the hash key is a boolean representing whther
the pseudo-class is supported or not.  Any pseudo-class not supported
by both the parser and the implementation (as declared by this
parameter) are ignored and the entire group of selectors is considered
I<invalid> for the purpose of parsing.

=item $parser->{pseudo_element} = {element_name => 1, element_name => 1, ...}

The list of pseudo-elements supported by the implementation,
represented as a hash reference, where the hash key is the lowercased
pseudo-element name and the hash key is a boolean representing whther
the pseudo-lelement is supported or not.  Any pseudo-element not
supported by both the parser and the implementation (as declared by
this parameter) are ignored and the entire group of selectors is
considered I<invalid> for the purpose of parsing.

=back

=head1 DATA STRUCTURES

=head2 A group of selectors

The C<parse_string> method returns an array reference, which contains
one or more selector data structures.  They corresponds to selectors
in the original group of selectors string, in order.

=head2 A selector

A selector is represented as an array reference, which contains pairs
of a combinator constant and a sequence of simple selector data
structure.  They corresponds to sequences of simple selector and
combinators appears in the original selector string, in order.  Note
that the first (index 0) item is always the descendant combinator
constant.

The constants below represent the types of combinators.

=over 4

=item DESCENDANT_COMBINATOR

A descendant combinator.

=item CHILD_COMBINATOR

A child combinator.

=item ADJACENT_SIBLING_COMBINATOR

An adjacent sibling combinator.

=item GENERAL_SIBLING_COMBINATOR

A general sibling combinator.

=back

The exporter tag C<:combinator> can be used to export all of these
constants:

  use Whatpm::CSS::SelectorsParser qw(:combinator);

=head2 A sequence of simple selectors

A sequence of simple selector is represented as an array reference,
which contains simple selector data strucutures.  They corresponds to
simple selectors in the original sequence of simple selectors string,
in order.

=head2 A simple selector

A simple selector is represented as an array reference whose first
(index 0) item is the type of simple selector and the following items
are arguments to the simple selector.

The constants below represent the types of simple selectors (or parts
of simple selectors).

=over 4

=item NAMESPACE_SELECTOR

The namespace specification in a type of universal selector.  The
first argument (item of index 1) is the namespace URL (or C<undef> for
the null namespace).

=item LOCAL_NAME_SELECTOR

The local name specification in a type selector.  The first argument
(item of index 1) is the local name.

=item ID_SELECTOR

An ID selector.  The first argument (item of index 1) is the ID.

=item CLASS_SELECTOR

A class selector.  The first argument (item of index 1) is the class.

=item PSEUDO_CLASS_SELECTOR

A pseudo-class selector.  The first argument (item of index 1) is the
pseudo-class name in lowercase.  If the pseudo-class takes a string or
identifier argument (e.g. C<:lang()> or C<:contains()>), the second
argument (item of index 2) is the argument (with no case folding).
Otherwise, if the pseudo-class takes a C<an+b> argument
(e.g. C<:nth-child()>), the second argument (item of index 2)
represents the I<a> value and the third argument (item of index 3)
represents the I<b> value (Even an incomplete argument is normalized
to this form).  If the pseudo-class takes a simple selector
(e.g. C<:not()>), any arguments (the zero or more items with index 2
or more) are simple selector data structures.

For example, the simple selector data structure for C<:NOT(a|b)> would
contain four items: constant C<PSEUDO_CLASS_SELECTOR>, string C<not>,
the namespace selector for the namespace I<a>, the local name selector
with local name C<b>.

=item PSEUDO_ELEMENT_SELECTOR

A pseudo-element specification.  The first argument (item of index 1)
is the pseudo-element name in lowercase.

=item ATTRIBUTE_SELECTOR

An attribute selector.  The first argument (item of index 1) is the
attribute name.  The second argument (item of index 2) is the type of
matching.

The constants below represent the types of matches used in attribute
selectors.

=over 4

=item EXISTS_MATCH

Match by the existence of an attribute.

=item EQUALS_MATCH

Exact match.  The third argument (item of index 3) is the expected
value.

=item INCLUDES_MATCH

Includes match (typically used for class attributes).  The third
argument (item of index 3) is the expected value.

=item DASH_MATCH

Dash match (typically used for language tag attributes).  The third
argument (item of index 3) is the expected value.

=item PREFIX_MATCH

Prefix match.  The third argument (item of index 3) is the expected
value.

=item SUFFIX_MATCH

Suffix match.  The third argument (item of index 3) is the expected
value.

=item SUBSTRING_MATCH

Substring match.  The third argument (item of index 3) is the expected
value.

=back

The exporter tag C<:match> can be used to export all of these
constants:

  use Whatpm::CSS::SelectorsParser qw(:match);

=back

The exporter tag C<:selector> can be used to export all of these
constants:

  use Whatpm::CSS::SelectorsParser qw(:selector);

=head1 SEE ALSO

Selectors <http://www.w3.org/TR/selectors/>.

The CSS syntax <http://www.w3.org/TR/CSS21/syndata.html>.

The C<style> attribute specificity
<http://www.w3.org/TR/CSS21/cascade.html#specificity>.

Supported standards - Selectors
<http://suika.fam.cx/gate/2007/html/standards#selectors>.

=head1 AUTHOR

Wakaba <w@suika.fam.cx>.

=head1 LICENSE

Copyright 2007-2011 Wakaba <w@suika.fam.cx>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
