use strict;
use warnings;
no warnings 'utf8';
use Path::Class;
use lib file (__FILE__)->dir->parent->parent->subdir ('lib')->stringify;
use lib glob file (__FILE__)->dir->parent->parent->subdir ('t_deps', 'modules', '*', 'lib')->stringify;
use Test::X1;
use Test::More;
use Web::CSS::Selectors::Serializer;
use Web::CSS::Parser;

for my $test (
  {in => [[DESCENDANT_COMBINATOR, []]],
   out => '*'},
  {in => [[DESCENDANT_COMBINATOR, [[LOCAL_NAME_SELECTOR, 'hoge']]]],
   out => 'hoge'},
  {in => [[DESCENDANT_COMBINATOR, [[LOCAL_NAME_SELECTOR, 'ho ge"'."\x0A"]]]],
   out => 'ho\\ ge\\"\\a '},
  {in => [[DESCENDANT_COMBINATOR, [[NAMESPACE_SELECTOR, 'http://hoge/', 'ho ge"'."\x0A"]]]],
   out => 'ho\\ ge\\"\\a |*'},
  {in => [[DESCENDANT_COMBINATOR, [[NAMESPACE_SELECTOR, '', 'ho ge"'."\x0A"]]]],
   out => '|*'},
  {in => [[DESCENDANT_COMBINATOR, [[NAMESPACE_SELECTOR, '', undef]]]],
   out => '*'},
  {in => [[DESCENDANT_COMBINATOR, [[NAMESPACE_SELECTOR, 'http://hoge/', undef]]]],
   out => '*'},
  {in => [[DESCENDANT_COMBINATOR, [[NAMESPACE_SELECTOR, undef, undef]]]],
   out => '|*'},
  {in => [[DESCENDANT_COMBINATOR, [[NAMESPACE_SELECTOR, undef, undef], [LOCAL_NAME_SELECTOR, 'hoge']]]],
   out => '|hoge'},
  {in => [[DESCENDANT_COMBINATOR, [[NAMESPACE_SELECTOR, undef, undef], [LOCAL_NAME_SELECTOR, 'ho ge']]]],
   out => '|ho\\ ge'},
  {in => [[DESCENDANT_COMBINATOR, [[NAMESPACE_SELECTOR, '', undef], [LOCAL_NAME_SELECTOR, 'ho ge']]]],
   out => 'ho\\ ge'},
  {in => [[DESCENDANT_COMBINATOR, [[NAMESPACE_SELECTOR, '', 'abc'], [LOCAL_NAME_SELECTOR, 'ho ge']]]],
   out => '|ho\\ ge'},
  {in => [[DESCENDANT_COMBINATOR, [[NAMESPACE_SELECTOR, 'http://hoge/', undef], [LOCAL_NAME_SELECTOR, 'ho ge']]]],
   out => 'ho\\ ge'},
  {in => [[DESCENDANT_COMBINATOR, [[NAMESPACE_SELECTOR, 'http://hoge/', 'ab cd'], [LOCAL_NAME_SELECTOR, 'ho ge']]]],
   out => 'ab\\ cd|ho\\ ge'},
  {in => [[DESCENDANT_COMBINATOR, [[ID_SELECTOR, 'ab!cd']]]],
   out => '#ab\\!cd'},
  {in => [[DESCENDANT_COMBINATOR, [[ID_SELECTOR, '1ab!cd']]]],
   out => '#\\31 ab\\!cd'},
  {in => [[DESCENDANT_COMBINATOR, [[CLASS_SELECTOR, 'ab!cd']]]],
   out => '.ab\\!cd'},
  {in => [[DESCENDANT_COMBINATOR, [[NAMESPACE_SELECTOR, undef, undef],
                                   [ID_SELECTOR, 'ab!cd']]]],
   out => '|*#ab\\!cd'},
  {in => [[DESCENDANT_COMBINATOR, [[NAMESPACE_SELECTOR, '', ''],
                                   [ID_SELECTOR, 'ab!cd']]]],
   out => '#ab\\!cd'},
  {in => [[DESCENDANT_COMBINATOR, [[NAMESPACE_SELECTOR, '', '12a'],
                                   [ID_SELECTOR, 'ab!cd']]]],
   out => '|*#ab\\!cd'},
  {in => [[DESCENDANT_COMBINATOR, [[NAMESPACE_SELECTOR, 'http://hoge/', '12a'],
                                   [ID_SELECTOR, 'ab!cd']]]],
   out => '\\31 2a|*#ab\\!cd'},
  {in => [[DESCENDANT_COMBINATOR, [[NAMESPACE_SELECTOR, 'http://hoge/', ''],
                                   [ID_SELECTOR, 'ab!cd']]]],
   out => '#ab\\!cd'},
  {in => [[DESCENDANT_COMBINATOR, [[NAMESPACE_SELECTOR, 'http://hoge/', ''],
                                   [CLASS_SELECTOR, 'ab!cd']]]],
   out => '.ab\\!cd'},
  {in => [[DESCENDANT_COMBINATOR, [[ATTRIBUTE_SELECTOR, undef, 'ab!cd',
                                    EXISTS_MATCH]]]],
   out => '[*|ab\\!cd]'},
  {in => [[DESCENDANT_COMBINATOR, [[ATTRIBUTE_SELECTOR, '', 'ab!cd',
                                    EXISTS_MATCH]]]],
   out => '[ab\\!cd]'},
  {in => [[DESCENDANT_COMBINATOR, [[ATTRIBUTE_SELECTOR, 'http://ho/', 'ab!cd',
                                    EXISTS_MATCH, undef, 'fu ga']]]],
   out => '[fu\\ ga|ab\\!cd]'},
  {in => [[DESCENDANT_COMBINATOR, [[ATTRIBUTE_SELECTOR, 'http://ho/', 'ab!cd',
                                    EQUALS_MATCH, '"\\'."\x0A", 'fu ga']]]],
   out => '[fu\\ ga|ab\\!cd="\\"\\\\\\a "]'},
  {in => [[DESCENDANT_COMBINATOR, [[ATTRIBUTE_SELECTOR, 'http://ho/', 'ab!cd',
                                    INCLUDES_MATCH, '"\\'."\x0A", 'fu ga']]]],
   out => '[fu\\ ga|ab\\!cd~="\\"\\\\\\a "]'},
  {in => [[DESCENDANT_COMBINATOR, [[ATTRIBUTE_SELECTOR, 'http://ho/', 'ab!cd',
                                    DASH_MATCH, '"\\'."\x0A", 'fu ga']]]],
   out => '[fu\\ ga|ab\\!cd|="\\"\\\\\\a "]'},
  {in => [[DESCENDANT_COMBINATOR, [[ATTRIBUTE_SELECTOR, 'http://ho/', 'ab!cd',
                                    PREFIX_MATCH, '"\\'."\x0A", 'fu ga']]]],
   out => '[fu\\ ga|ab\\!cd^="\\"\\\\\\a "]'},
  {in => [[DESCENDANT_COMBINATOR, [[ATTRIBUTE_SELECTOR, 'http://ho/', 'ab!cd',
                                    SUFFIX_MATCH, '"\\'."\x0A", 'fu ga']]]],
   out => '[fu\\ ga|ab\\!cd$="\\"\\\\\\a "]'},
  {in => [[DESCENDANT_COMBINATOR, [[ATTRIBUTE_SELECTOR, 'http://ho/', 'ab!cd',
                                    SUBSTRING_MATCH, '"\\'."\x0A", 'fu ga']]]],
   out => '[fu\\ ga|ab\\!cd*="\\"\\\\\\a "]'},
  {in => [[DESCENDANT_COMBINATOR, [[ATTRIBUTE_SELECTOR, '', 'ab!cd',
                                    EQUALS_MATCH, '"\\'."\x0A", 'fu ga']]]],
   out => '[ab\\!cd="\\"\\\\\\a "]'},
  {in => [[DESCENDANT_COMBINATOR, [[ATTRIBUTE_SELECTOR, 'http://ho/', 'ab!cd',
                                    EQUALS_MATCH, '', 'fu ga']]]],
   out => '[fu\\ ga|ab\\!cd=""]'},
  {in => [[DESCENDANT_COMBINATOR, [[PSEUDO_CLASS_SELECTOR, 'active']]]],
   out => ':active'},
  {in => [[DESCENDANT_COMBINATOR, [[PSEUDO_CLASS_SELECTOR, 'only-child']]]],
   out => ':only-child'},
  {in => [[DESCENDANT_COMBINATOR, [[PSEUDO_CLASS_SELECTOR, 'lang', 'a"']]]],
   out => ':lang(a\\")'},
  {in => [[DESCENDANT_COMBINATOR, [[PSEUDO_CLASS_SELECTOR, 'lang', 'ja-JP']]]],
   out => ':lang(ja-JP)'},
  {in => [[DESCENDANT_COMBINATOR, [[PSEUDO_CLASS_SELECTOR, '-manakai-contains',
                                    '']]]],
   out => ':-manakai-contains("")'},
  {in => [[DESCENDANT_COMBINATOR, [[PSEUDO_CLASS_SELECTOR, '-manakai-contains',
                                    'ja \\'."\x0F"]]]],
   out => ':-manakai-contains("ja \\\\\\f ")'},
  {in => [[DESCENDANT_COMBINATOR, [[PSEUDO_CLASS_SELECTOR, 'not',
     [[DESCENDANT_COMBINATOR, [[LOCAL_NAME_SELECTOR, 'a']]],
      [DESCENDANT_COMBINATOR, [[CLASS_SELECTOR, 'b c']],
       ADJACENT_SIBLING_COMBINATOR, [[ID_SELECTOR, '1']]]],
   ]]]],
   out => ':not(a, .b\\ c + #\\31 )'},
  {in => [[DESCENDANT_COMBINATOR, [[PSEUDO_CLASS_SELECTOR, 'not',
     [[DESCENDANT_COMBINATOR, [[NAMESPACE_SELECTOR, undef, undef],
                               [LOCAL_NAME_SELECTOR, 'a']]],
      [DESCENDANT_COMBINATOR, [[CLASS_SELECTOR, 'b c']],
       ADJACENT_SIBLING_COMBINATOR, [[ID_SELECTOR, '1']]]],
   ]]]],
   out => ':not(|a, .b\\ c + #\\31 )'},
  {in => [[DESCENDANT_COMBINATOR, [[PSEUDO_CLASS_SELECTOR, 'not',
     [[DESCENDANT_COMBINATOR, [[NAMESPACE_SELECTOR, '', ''],
                               [LOCAL_NAME_SELECTOR, 'a']]],
      [DESCENDANT_COMBINATOR, [[CLASS_SELECTOR, 'b c']],
       ADJACENT_SIBLING_COMBINATOR, [[ID_SELECTOR, '1']]]],
   ]]]],
   out => ':not(a, .b\\ c + #\\31 )'},
  {in => [[DESCENDANT_COMBINATOR, [[PSEUDO_CLASS_SELECTOR, 'nth-child',
                                    '010', '0002']]]],
   out => ':nth-child(10n+2)'},
  {in => [[DESCENDANT_COMBINATOR, [[PSEUDO_CLASS_SELECTOR, 'nth-child',
                                    '010', '000']]]],
   out => ':nth-child(10n)'},
  {in => [[DESCENDANT_COMBINATOR, [[PSEUDO_CLASS_SELECTOR, 'nth-child',
                                    '-0', '0002']]]],
   out => ':nth-child(2)'},
  {in => [[DESCENDANT_COMBINATOR, [[PSEUDO_CLASS_SELECTOR, 'nth-child',
                                    '00', '-000']]]],
   out => ':nth-child(0)'},
  {in => [[DESCENDANT_COMBINATOR, [[PSEUDO_CLASS_SELECTOR, 'nth-child',
                                    '+0', '+0002']]]],
   out => ':nth-child(2)'},
  {in => [[DESCENDANT_COMBINATOR, [[PSEUDO_CLASS_SELECTOR, 'nth-child',
                                    '-0', '-0002']]]],
   out => ':nth-child(-2)'},
  {in => [[DESCENDANT_COMBINATOR, [[PSEUDO_CLASS_SELECTOR, 'nth-of-type',
                                    '-013', '000']]]],
   out => ':nth-of-type(-13n)'},
  {in => [[DESCENDANT_COMBINATOR, [[PSEUDO_CLASS_SELECTOR, 'nth-last-child',
                                    '-013', '0002']]]],
   out => ':nth-last-child(-13n+2)'},
  {in => [[DESCENDANT_COMBINATOR, [[PSEUDO_CLASS_SELECTOR, 'nth-last-of-type',
                                    '-013', '-0002']]]],
   out => ':nth-last-of-type(-13n-2)'},
  {in => [[DESCENDANT_COMBINATOR, [[PSEUDO_ELEMENT_SELECTOR, 'before']]]],
   out => '::before'},
  {in => [[DESCENDANT_COMBINATOR, [[PSEUDO_ELEMENT_SELECTOR, 'first-line']]]],
   out => '::first-line'},
  {in => [[DESCENDANT_COMBINATOR, [[PSEUDO_ELEMENT_SELECTOR, 'cue']]]],
   out => '::cue'},
  {in => [[DESCENDANT_COMBINATOR, [[PSEUDO_ELEMENT_SELECTOR, 'cue',
     [[DESCENDANT_COMBINATOR, [[NAMESPACE_SELECTOR, undef, undef],
                               [LOCAL_NAME_SELECTOR, 'a']]],
      [DESCENDANT_COMBINATOR, [[CLASS_SELECTOR, 'b c']],
       ADJACENT_SIBLING_COMBINATOR, [[ID_SELECTOR, '1']]]],
   ]]]],
   out => '::cue(|a, .b\\ c + #\\31 )'},
  {in => [[DESCENDANT_COMBINATOR, [[PSEUDO_CLASS_SELECTOR, 'nth-child',
                                    '010', '0002']],
           CHILD_COMBINATOR, [[PSEUDO_ELEMENT_SELECTOR, 'first-line']]]],
   out => ':nth-child(10n+2) > ::first-line'},
  {in => [[DESCENDANT_COMBINATOR, [[LOCAL_NAME_SELECTOR, 'cd']],
           CHILD_COMBINATOR, [[CLASS_SELECTOR, 'line']],
           GENERAL_SIBLING_COMBINATOR, [[ID_SELECTOR, '_']]]],
   out => 'cd > .line ~ #_'},
  {in => [[DESCENDANT_COMBINATOR, [[LOCAL_NAME_SELECTOR, 'cd']],
           CHILD_COMBINATOR, [[CLASS_SELECTOR, 'line']],
           GENERAL_SIBLING_COMBINATOR, [[ID_SELECTOR, '_']]],
          [DESCENDANT_COMBINATOR, [[LOCAL_NAME_SELECTOR, 'f'],
                                   [PSEUDO_CLASS_SELECTOR, 'enabled']],
           ADJACENT_SIBLING_COMBINATOR, [[ID_SELECTOR, '12']]]],
   out => 'cd > .line ~ #_, f:enabled + #\31 2'},
) {
  test {
    my $c = shift;
    my $s = Web::CSS::Selectors::Serializer->new;
    is $s->serialize_selectors ($test->{in}), $test->{out};
    done $c;
  } n => 1, name => ['serialize_selectors', $test->{out}];
}

run_tests;

=head1 LICENSE

Copyright 2013 Wakaba <wakaba@suikawiki.org>.

This program is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
