=head1 NAME

Web::CSS::Props - CSS property definitions

=head1 DESCRIPTION

XXX

=head1 SPECIFICATIONS

=over 4

=item CSSSYNTAX

CSS Syntax <http://dev.w3.org/csswg/css-syntax/#integer>.

=item QUIRKS

Quirks Mode <http://quirks.spec.whatwg.org/>.

=item CSSOM

CSS Object Model (CSSOM) <http://dev.w3.org/csswg/cssom/>.

=item CSSCASCADE

CSS Cascading and Inheritance <http://dev.w3.org/csswg/css-cascade/>.

=item CSSVALUES

CSS Values and Units <http://dev.w3.org/csswg/css-values/>.

=item CSSCOLOR

CSS Color <http://dev.w3.org/csswg/css-color/>.

The '-webkit-opacity' property MUST be parsed as if it were the
'opacity' property.

=item CSSBACKGROUNDS

CSS Background and Borders <http://dev.w3.org/csswg/css-backgrounds/>.

To serialize the 'border-color' property value, follow the steps to
serialize four edge values with 'border-top-color',
'border-right-color', 'border-bottom-color', and 'border-left-color'
values and return the result.

To serialzie four edge values /top/, /right/, /bottom/, and /left/,
follow these steps:

  1. If one of four values is missing, it is not serializable.  Return
     null and abort these steps.

  2. Otheriwse, if one of four values is CSS-wide keyword or function:

    1. If serializations of four values are same, return one of them
       and abort these steps.

    2. Otherwise, it is not serializable.  Return null and abort these
       steps.

  3. Otherwise, if serializations of four values are same, return one
     of them and abort these steps.

  4. Otherwise, if serializations of /top/ and /bottom/ are same and
     serialization of /left/ and /right/ are same, return the result
     of invoking serialize a whitespace-separated list with values
     /top/ and /right/ and abort these steps.

  5. Otherwise, if serialization of /left/ and /right/ are same,
     return the result of invoking serialize a whitespace-separated
     list with values /top/, /right/, and /bottom/ and abort these
     steps.

  6. Otherwise, return the result of invoking serialize a
     whitespace-separated list with values /top/, /right/, /bottom/,
     and /left/ and abort these steps.

=item CSSDISPLAY

CSS Diaplay <http://dev.w3.org/csswg/css-display/>.

=item CSSBOX

CSS Basic Box Model <http://dev.w3.org/csswg/css-box/>.

In 'width', 'min-width', and 'max-width' properties, keywords
'-moz-available', '-moz-fit-content', '-moz-min-content', and
'-moz-max-content' MUST be replaced by corresponding keywords without
"-moz-" prefix at parse time.

In 'width', 'min-width', 'max-width', 'height', 'min-height', and
'max-height' properties, keywords '-webkit-fit-content',
'-webkit-min-content', and '-webkit-max-content' MUST be replaced by
corresponding keywords without "-webkit-" prefix at parse time.

=item CSSPOSITION

CSS Positioned Layout <http://dev.w3.org/csswg/css-position/>.

=item CSSOVERFLOW

CSS Overflow <http://dev.w3.org/csswg/css-overflow/>.

To serialize the 'overflow' property value, follow these steps:

  1. If 'overflow-x' or 'overflow-y' is missing, it is not
     serializable.  Return null and abort these steps.

  2. Otherwise, if serialization of 'overflow-x' is equal to
     serialization of 'overflow-y', return one of them.

  3. Otherwise, it is not serializable.  Return null.

=item CSSBREAK

CSS Fragmentation <http://dev.w3.org/csswg/css-break/>.

=item CSSWRITINGMODES

CSS Writing Modes <http://dev.w3.org/csswg/css-writing-modes/>.

=item CSSLISTS

CSS Lists and Counters <http://dev.w3.org/csswg/css-lists/>.

=item CSSCOUNTERSTYLES

CSS Counter Styles <http://dev.w3.org/csswg/css-counter-styles/>.

=item CSSUI

CSS Basic User Interface <http://dev.w3.org/csswg/css-ui/>.

=item CSSTEXT

CSS Text <http://dev.w3.org/csswg/css-text/>.

=item CSSFONTS

CSS Fonts <http://dev.w3.org/csswg/css-fonts/>.

The '-webkit-xxx-large' keyword can be used as <absolute-size>.

=item CSS21

CSS 2.1 <http://www.w3.org/TR/CSS21/tables.html>.

=item CSS20

CSS 2 <http://www.w3.org/TR/1998/REC-CSS2-19980512/>.

=item MANAKAICSS

manakai CSS Extensions
<http://suika.suikawiki.org/~wakaba/wiki/sw/n/manakai%20CSS%20Extensions>.

The '-webkit-border-horizontal-spacing' and
'-webkit-border-vertical-spacing' properties are defined as follows:

  Value:          <length>
  Initial:        0
  Applies to:     Same as 'border-spacing'
  Inherited:      yes
  Percentage:     N/A
  Media:          Visual
  Computed value: Absolute length

The 'border-spacing' property is redefined as the shorthand of these
two properties.  To serialize the 'border-spacing' property values,
run following steps:

  1. If one of '-webkit-border-horizontal-spacing' and
     '-webkit-border-vertical-spacing' is missing, it is not
     serializable.  Return null.

  2. Otherwise, if serialization of
     '-webkit-border-horizontal-spacing' and
     '-webkit-border-vertical-spacing' are equal, return one of them.

  3. Otherwise, if one of '-webkit-border-horizontal-spacing' and
     '-webkit-border-vertical-spacing' is a CSS-wide keyword or
     function, it is not serializable.  Return null.

  4. Otherwise, return the result of invoking serialize a
     whitespace-separated list with serializations of
     '-webkit-border-horizontal-spacing' and
     '-webkit-border-vertical-spacing',

=back

=head1 OBSOLETE FEATURES

Support for following feature has been removed: Keywords
'-moz-pre-wrap', '-moz-use-text-color', '-o-pre-wrap', and
'-webkit-marquee', and property '-moz-opacity'.

=head1 SEE ALSO

L<Web::CSS::Values>.

L<Web::CSS::Parser>, L<Web::CSS::Serializer>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2007-2013 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
