=head1 NAME

Web::CSS::Tokenizer - A CSS tokenizer

=head1 DESCRIPTION

The C<Web::CSS::Tokenizer> module provides a CSS syntax tokenizer.  It
can be used to tokenize strings written in languages using the CSS
syntax, including CSS, Selectors, and Media Queries.

=head1 SEE ALSO

CSS 2.1 <http://www.w3.org/TR/CSS2/>.

Selectors <http://www.w3.org/TR/selectors>.

L<Web::CSS::Parser>, L<Web::CSS::Selectors::Parser>,
L<Web::CSS::MQ::Parser>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2007-2013 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
