=head1 NAME

Web::CSS::Values - CSS value definitions

=head1 DESCRIPTION

XXX

=head1 SPECIFICATIONS

=over 4

=item CSSVALUES

CSS Values and Units <http://dev.w3.org/csswg/css-values/>.

The parser MUST convert non-keyword <color> values to the |rgba()|
functional notation.

The parser MUST interpret <length> value '0' as '0px'.

The number of <resolution> must be positive.

=item CSSSYNTAX

CSS Syntax <http://dev.w3.org/csswg/css-syntax/#integer>.

=item MQ

Media Queries <http://dev.w3.org/csswg/mediaqueries/#values>.

=back

=head1 SEE ALSO

L<Web::CSS::Props>, L<Web::CSS::MediaQueries::Features>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>.

=head1 LICENSE

Copyright 2007-2013 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
